name: Ruby test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    services:
      activemq:
        image: apache/activemq-classic:6.1.0
        ports:
          - 28161:8161
          - 21613:61613
      challenge-server:
        image: wiremock/wiremock:3.7.0
        ports:
          - 8222:8080
      recording-server:
        image: wiremock/wiremock:3.7.0
        ports:
          - 41375:8080

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      # ~~~~~~~~~~~~~ Ruby setup ~~~~~~~~~~~~~
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # Adjust to your Ruby version
          bundler-cache: true

      - name: Display Ruby version
        run: ruby -v

      - name: Install dependencies
        run: bundle install

      # ~~~~~~~~~~~~~ Test ~~~~~~~~~~~~~
      - name: Run tests
        run: bundle exec rake features
