name: Create GitHub Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ~~~~~~~~~~~~~ Ruby setup ~~~~~~~~~~~~~
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # adjust as needed
          bundler-cache: true

      - name: Display Ruby version
        run: ruby -v

      - name: Install dependencies
        run: bundle install

      # ~~~~~~~~~~~~~ Build the gem ~~~~~~~~~~~~~
      - name: Build gem
        run: gem build tdl-client-ruby.gemspec

      - name: Rename gem for consistency
        run: |
          mkdir -p pkg
          mv *.gem pkg/tdl-client-ruby.gem

      # ~~~~~~~~~~~~~ Create GitHub Release ~~~~~~~~~~~~~
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pkg/tdl-client-ruby.gem
